### ISSUE TITLE
[Grades Server Module] Be more specific in finding directory IDs

### ISSUE THREAD

**Issue by msimmon6** [Algomorph/CodeGrader#108]
**Describe the bug**
Currently, the way directory IDs are found in the server just finds if a table element contains the ID, but issues arise if the ID is a substring of another ID.

**Where did the bug occur**
This occurs with student ID "ice" from Lingjia Li and "aprice16" from Aaron Price.

**Additional info**
I think it's a simple fix on line 80 of grades_server_main.js but I don't know Node.js to change "contains" to something similar to "equals" :)

**Comment by msimmon6** [comment]
Also "ishi" in "sairishi"

**Comment by Algomorph** [comment]
@william8siew , could you take care of this? Probably, a matter of using a whole-match regex (with ^ in the beginning and $ at the end) instead of just using `.includes`

**Comment by william8siew** [comment]
Am going to tackle this now

**Comment by william8siew** [comment]
I will submit a PR and I just changed the jquery string from td:contains to td:eq which finds the first exact match. Ideally someone could test it using the submit server with the substring type id's . If this doesn't work, I can add some custom jquerys meant for exact matching like here: http://wowmotty.blogspot.com/2010/05/jquery-selectors-adding-contains-exact.html

**Comment by william8siew** [comment]
I did the custom jquery option and it works on my end. Please test it with those cases when possible @Algomorph @msimmon6

**Comment by Algomorph** [comment]
Ah, this is fantastic! Thank you for the fix, @william8siew!
And thank you @msimmon6 for reviewing & closing the issue. Sorry I've been away yesterday most of the day.
