### ISSUE TITLE
Fix JSON5 pretty format to include comments

### ISSUE THREAD

**Issue by william8siew** [Algomorph/CodeGrader#110]
JSON5 can't pretty format automatically wihtout removing comments. 
https://github.com/rhysd/fixjson might be useful in figuring out how to preserve thse

**Comment by Algomorph** [comment]
I did another look-around, seems like `https://github.com/beautify-web/js-beautify` just might do the trick. It is, however, a node module, so I'm not sure in what capacity it can be used (I've read bad things about trying to incorporate node into a Chrome plugin before).

**Comment by william8siew** [comment]
oh that's smart. formatting json as javascript should work. I'm sure it's possible to use the beautify script without needing to install the node modules. It says u can use it from their web library so im guessing you might just be able to install it locally?

**Comment by Algomorph** [comment]
Good point. Will try.
