### ISSUE TITLE
Integrate with node.js.

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#116]
It *is* actually possible to develop chrome extensions using node.js. See post here: https://stackoverflow.com/questions/12575965/is-it-possible-to-develop-google-chrome-extensions-using-node-js

The reason we want this is it will help us use `jest` for testing (#74) and `js-beautify` for re-formatting JSON5 (#110).

We need to look into this and figure out how to do this right, if it truly is possible and won't destroy things.

**Comment by Algomorph** [comment]
Deliverables:

Level one:
Set up `npm` package config files in repo root, so that as able to run `jest` in the code repo root (offline). You'll have to make an example test case in a separate file.
Eg, you can put it in `tests/test_test.js`. Note that `jest` is a node.js package.

Level two:
See if you can run another node package, `js-beautify`, online. E.g. you can try tackling the #110 directly and apply the formatter to the options after the user hits "Save" and before the options get stored.

**Comment by Algomorph** [comment]
Feel free to adjust the deliverables as you see fit as long as the end-goals (running node packages offline & online) are fulfilled.

**Comment by Algomorph** [comment]
@msimmon6 , just took a look at your branch. Two comments:
1) `node_modules` really shouldn't be in the repo. It should be automatically set up when you initialize node within the package. To make sure it doesn't give you the filter-out-during-commit hassle every time, there are two ways: (a) add to .gitignore and (b) add to global .gitignore on your machine. I think it's probably wiser to add to .gitignore.
2) The compiled "bundle.js"
    -  First, the name seems iffy and undescriptive. If this is the file derived from options / options controller, can we just rename that to something like "options_compiled.js" for now? 
    - Secondly, there's the observation that we need to keep that in the repo (even though it's derived / "complied" code), because we still want people to be able to install the plugin from the GitHub repo directly, without going through the extra steps of setting up node and compiling the thing. 
    - Finally, there's this question: will we have to compile _multiple_ files into a single "bundle" file in order to use multiple node modules in other places within the project? I think we can probably wait on that until we need to address that question directly, but let's keep ourselves open to the possibility right away that the entire (or most) javascript in the repository might later need to be compiled into a single file -- with only that file then used in the manifest. Does that make sense?

**Comment by msimmon6** [comment]
1. Yeah, I can do that - I just wanted to make sure I wasn't missing anything critical.

2a. I just went with what the examples used as the name since I was having issues with it. I can definitely rename it.

2b. Yeah, it could be redundant. Since the "compiled" code clearly just copy-pastes the original code, we could just remove the original file and modify our browserified file, as it has all we need in terms of replacing "required" with non-node code.

2c. We could compile multiple files into one file if needed. I believe we can just compile them into separate browserified files.

**Comment by Algomorph** [comment]
For 2b, I think we kinda have to do the ugly here for now and leave both files in the repo, in case we want to modify the original source. I just want people to be able to install the app in developer mode, from the repo, for now.
