### ISSUE TITLE
[Method call module] calling static type name not resolved properly

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#117]
**Describe the bug**
Utility.findOddMin in code resolved as type.findOddMin

**Where did the bug occur**
Instructor & Course: Pedram's CMSC131
Project name on Submit Server: Quiz 5
Student directory id: bdevarsu

**Additional info**
Remember to get rid of "type.findOddMin" in the Method Call Module options to see how the bug manifests itself.

**Comment by msimmon6** [comment]
I've found where it occurs and now changed it to Utilities.findOddMin, I am unsure as to whether the original "type" is important but it is now removed.

**Comment by Algomorph** [comment]
Thank you!
The "type.findOddMin" shouldn't cause trouble, but should be fixed in the template at some point. I'll make a note.
Fixed by #118
