### ISSUE TITLE
Do not generate feedback link if there is no feedback

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#121]
This is something between a bug and an enhancement. Unless you save a comment, the review link that's auto-posted to the comments section for a student on the grade server will lead to nowhere.

We should just avoid generating the link if there are no comments.

**Comment by Algomorph** [comment]
@william8siew , can you handle this? Should be a quick fix.

**Comment by william8siew** [comment]
Will take a look after my finals exams this week
