### ISSUE TITLE
Invisible character still in MethodCalls

### ISSUE THREAD

**Issue by msimmon6** [Algomorph/CodeGrader#127]
**Describe the bug**
I noticed that the tests for gcrevass' proj 6 in the Spring 2021 CMSC131 were not picking up the methods which were clearly being called. Upon investigation I found that the methodCalls had an invisible character (\u200B) at the end of some of the names.

**Where did the bug occur**
Pedram's CMSC131
Proj 6
gcrevass

**Desktop (please complete the following information):**
Windows

**Additional info**
I feel like this may be a simple fix in the naming module / wherever the methodCalls of a TypeInformation are created. I didn't want to fix it myself in case it made pushing your naming module stuff an issue, so hopefully you can fix it quickly in your branch.

**Comment by Algomorph** [comment]
Good catch! We had a similar problem in the names module at some point. There's a workaround there that can guide the fix here, within the `checkName` method.
