### ISSUE TITLE
Report to grade server fails if project name includes text enclosed in parentheses

### ISSUE THREAD

**Issue by solarlight2** [Algomorph/CodeGrader#130]
**Describe the bug**
In the grade server module, if the name of the project contains something enclosed in parentheses, the call to the grade server fails since it's assumed that the student's directory ID is the only thing enclosed in parentheses in the header and so it incorrectly uses the part of the project name enclosed in parentheses as the directory ID.

**Where did the bug occur**
Instructor & Course: [e.g. Fawzi CMSC131]
Project name on Submit Server: [Maryland Baseball]
Student directory id: [eabebe]

**Desktop (please complete the following information):**
 - OS: Windows

**Additional info**
It might do to just select the last thing enclosed in parentheses rather than just taking the first thing, -- maybe .split on spaces first, and then you can safely .split on the last index of the result, since we can probably assume that the directory ID should be the last word in the header.

**Comment by Algomorph** [comment]
Seems related (but different from) #131

**Comment by Algomorph** [comment]
Fixed in 7c52eb5c770199a335eee39b3640b50b9fcbc703. Please, instruct all TAs in the course to use the development version that has the fixes! The [installation](https://github.com/Algomorph/CodeGrader#installation-from-source) should be very quick and straightforward.
