### ISSUE TITLE
[Indentation Module] Properly handle mixed Tabs & Spaces

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#147]
When students mix tabs & spaces, this results in grading disputes. E.g. CodeGrader marks these lines as having indentation problems, but the student doesn't see anything wrong with the spacing in his editor or up on the submit server.

**Describe the solution you'd like**
The best solution would be to explicitly detect when the student has mixed tabs and spaces. If such is the case for a specific line, then a completely different problem should be reported for that line -- regardless of any other indentation problems all around. This can be accomplished by extending `CodeEntity` in the `spacing_module.js` again with a new class, something like `MixedTabsAndSpacesIndent`, and accumulate + display these issues in a separate array as the file is being scanned. The detection itself can probably be easily done via regex and should precede any other checks. If the issue is detected, other checks should be short-circuited (but expected indentation level for the next line still tracked in case there are scope openings, e.g. '{', and such).

**Describe alternatives you've considered**
An alternative is to count the tab as a certain number of spaces and then add the actual spaces to come up with the indent number, and then keep hush about the issue if the resulting number matches expected indent length.

**Additional context**
Check out CMSC 131 projects for this issue. It should occur in their "Flags" Java project pretty heavily.

While in Eclipse or Visual Code, the indentation is correct:
![image](https://user-images.githubusercontent.com/1050606/149843537-2f24929a-a538-4514-9719-db328771b41e.png)
The indentation seems incorrect on the submit server:
![image](https://user-images.githubusercontent.com/1050606/149843543-2bb03ea3-085a-44dd-b0e4-5f7063c6532b.png)
Same problem when viewing the file in Vim:
![image](https://user-images.githubusercontent.com/1050606/149843549-bca83674-d8b6-442a-93eb-d8621b4d6c5b.png)

**Comment by msimmon6** [comment]
So the original problem isn't actually with the code - the code works fine with it! (The over-indent part appears to be a problem which has already been solved). This image shows the same code with working text.

![image](https://user-images.githubusercontent.com/72671782/149848376-0eb4f071-b698-4793-a0ab-2eeca3945f71.png)

I have made code which does the alternative solution since it seems nicer to me (If I were a 131 student, I would not care between spaces/tabs if what I see looks the same). I think the issue they want is that visually, it does not appear to be aligned. This should be fixed by injecting the following into the style: "pre { tab-size: 4; } ". Let me know if this is what you'd like me to do.

**Comment by Algomorph** [comment]
@msimmon6 , mixing tabs and spaces in code indents is absolutely a horrid practice. It is passable (although questionable, in terms of keyboard usage & general sanity) if you have a nice IDE and know how to use the auto-formatter to convert your indents to either tabs or spaces (depending on your preference), but we're still, unfortunately, in the era when using less-sophisticated text editors for coding is a common practice. And all hell breaks loose when you mix tabs + spaces and then someone opens your code in a different editor with a different tab-width default. 

I say we can strike a compromise here easily: let the default behavior be to treat mixed tabs & spaces a problem, but allow this to be overridden by a setting in module options, something like "ignoreMixedTabsAndSpaces:true", which will then also insert the `pre {tab-size: 4;}` into the code like you said.
