### ISSUE TITLE
Fix Mixed Tabs & Spaces being overzealous on Eclipse formatting for multiple lines

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#162]
In multi-line statements & expressions. Sometimes, Eclipse will tend to add a fixed number of spaces after a number of tabs to each line in order to align certain elements visually.

Example (observed awhile back):
```Java
String veryLongString = "Using the + operator is another way" 
                        + "of achieving the same thing." 
                        + "Java compilers translate concat()"
                        + "and the + operator in the same way"
```

**Comment by Algomorph** [comment]
The first step is to find some valid examples of this in student code (set the "Ignore Mixed Tabs & Spaces" setting to off in the plugin) and then test that that is indeed how Eclipse does the auto-formatting.

**Comment by msimmon6** [comment]
When coding the exact same example, I am getting only tabs. I will work further to find better examples.

**Comment by Algomorph** [comment]
Hmm.... Perhaps students are trying to replicate what eclipse does manually, and that's what I was actually seeing up on the server?
