### ISSUE TITLE
Null superclass type in determineMethodCallIdentifierAndCalledType

### ISSUE THREAD

**Issue by msimmon6** [Algomorph/CodeGrader#164]
**Describe the bug**

While testing a certain project, an interesting bug occurred. I was getting a 'null' value in a function which checks for 'undefined'. I'm unsure why this case specifically gives null as nothing looks too off by the project apart from a whole lot of comments:

Error handling response: TypeError: Cannot read properties of null (reading 'name')
    at Object.determineMethodCallIdentifierAndCalledType (chrome-extension://cnnkpiglmanjijoejphiiamodlpbidop/code_analysis/auxiliary_analytic_routines.js:295:81)
    at Object.findCodeComponentsInAstNode ...

**Where did the bug occur**

Semester: Spring 2022
Instructor & Course: Pedram's CMSC131
Project name on Submit Server: Proj 5
Student directory id: tduque

Code segment (if known & relevant): Somewhere in Address.java

**Additional info**

Adding an additional null-check makes the code work as far as I can tell.

The code literally does not appear to have anything weird apart from comments everywhere. This is my prime suspect.

**Comment by Algomorph** [comment]
I think I just fixed this with 7da6dcf640c553d0e88bed88fe9fe8591153e753. Since I don't have access to CMSC131 right now, could you verify the fix works on your end?

**Comment by msimmon6** [comment]
Sorry for the late response -- I checked and it's working now!
