### ISSUE TITLE
Detecting student tests failing

### ISSUE THREAD

**Issue by goldburger** [Algomorph/CodeGrader#165]
Latest commit failing to detect any student tests; had to revert to Chrome web store version to grade

Semester: Spring 22
Instructor & Course: Pedram/Nelson CMSC132
Project name on Submit Server: Proj 5
Student directory id: many, e.g. dbalakir and ddayan

**Comment by Algomorph** [comment]
Thanks, I am able to replicate this on `dbalakir` and `ddayan`. I will keep you updated.
