### ISSUE TITLE
Generate the untested summary inconsistent

### ISSUE THREAD

**Issue by goldburger** [Algomorph/CodeGrader#166]
Button to generate the untested summary for StudentTests is very inconsistent; at times clicking the box opens a blank text box instead of the report. Clicking repeatedly in slightly different regions of the box seems to eventually spawn the right summary, but may require many tries.

Semester: Spring 22
Instructor & Course: Pedram/Nelson CMSC132
Project name on Submit Server: Proj 5

**Comment by Algomorph** [comment]
This is most likely a Marmoset Submit Server issue, we'll avoid dealing with this until further notice.
