### ISSUE TITLE
False over-indent detected by indentation module, exact reasons unclear

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#168]
**Describe the bug**

False over-indent detected by indentation module.

**Where did the bug occur**

Semester: Spring 2022
Instructor & Course: Nelson's/Pedram's CMSC132
Project name on Submit Server: Project #6
Student directory id: shughes5

Code segment (if known & relevant):

```Java
    /* Returns a string generated as the grading report for a specified exam,
	 * formatted with information about that exam */
	public String getGradingReport(String studentName, int examID) {
		String answer = "";
		double totalPointsOnExam = 0;Variable totalPointsOnExam
		double totalPointsReceived = 0;Variable totalPointsReceived
		//iterate through each qustion of the exam
		for (int questionNumber = 1; questionNumber < getAllQuestionsFromExam
     									(examID).size() + 1; questionNumber++) {
			answer += "Question #" + questionNumber + " ";
     		answer += getPointsAchievedForQuestionOver-indent
     									  (studentName, examID, questionNumber);
     		answer += " points out of " + getQuestionFromExamOver-indent
     									   (examID, questionNumber).getPoints();
     		answer += "\n";Over-indent
     		totalPointsReceived += getPointsAchievedForQuestion
     									  (studentName, examID, questionNumber);
     		totalPointsOnExam += getQuestionFromExamOver-indent
     									   (examID, questionNumber).getPoints();
     		
		}
		answer += "Final Score: " + totalPointsReceived + " out of "
															+ totalPointsOnExam;
		return answer;
	}
```

**Additional info**

The false positive starts getting picked up on the second `answer += ....` line:

![image](https://user-images.githubusercontent.com/1050606/164773438-1dab7d4a-b752-4ae1-bf3b-25bd2dca9dc0.png)

**Comment by msimmon6** [comment]
I have found the issue -- it deals with mixing tabs and spaces. The student put the following in their line: "\s\s\s\s\s\t\t", or 5 spaces and 2 tabs. Since a tab really just brings to the next multiple of 4 and is not always 4 spaces, it sees this as 13 when it is really 12. This should not be hard to fix.
