### ISSUE TITLE
Parser Error in Exam 6

### ISSUE THREAD

**Issue by msimmon6** [Algomorph/CodeGrader#186]
**Describe the bug**

A parser error occurred while grading exams. Very interesting, as the UI does not say which file the error is in, and the file that should be tested has 1 less line than it says the error occurs on (has 114 lines, error on line 115), and also detects "p".

**Where did the bug occur**

Semester: Summer 2022
Instructor & Course: Pedram 132
Project name on Submit Server: Exam 6
Student directory id: jchu20

Code segment (if known & relevant):

![image](https://user-images.githubusercontent.com/72671782/179436577-e988ff8a-689d-427f-a681-aaa02b719d00.png)

**Additional info**

No idea what the issue is here.

**Comment by msimmon6** [comment]
Occurs also in sgoktepe

**Comment by Algomorph** [comment]
Hmm... Interesting... I remember there were some weird things with "missing last line". Something (maybe Java itself) needs a blank line, so I might have artificially added one in some cases. I'll look into this later. Thanks!

**Comment by msimmon6** [comment]
I now notice it occurs only in Online submissions (notice the files aren't in a package).

**Comment by msimmon6** [comment]
Nevermind -- the issue came from how I checked the files. When I do 'src/sysImplementation/RosterTree.java||RosterTree.java', it causes the above, but when I have them separate it works fine! 

We just need to stick with separating cases (but this causes another issue with the keyword module iirc)

**Comment by Algomorph** [comment]
Thanks for the work-around!
`src/sysImplementation/RosterTree.java||RosterTree.java` has two pipe characters (`|`) in it. Does the bug still occur if there is only one?

**Comment by msimmon6** [comment]
You're right -- it's all good with only one pipe character! I guess I just didn't read the documentation too well :-)

**Comment by Algomorph** [comment]
I guess this issue is resolved then? Feel free to reopen if it isn't.
