### ISSUE TITLE
Error in indentation module: `Cannot read property 'length' of null`

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#25]
This occurs on Proj 1 (use `cmsc132_BlackjackProject_GradingAid_options.json`) for amatikya.

**Comment by Algomorph** [comment]
![image](https://user-images.githubusercontent.com/1050606/96308021-94438800-0fd0-11eb-82b9-6e09882b6162.png)

**Comment by msimmon6** [comment]
I actually finished this a while ago and the commit works after fixing my Git yesterday :-)
