### ISSUE TITLE
Add label / continue loop detection into the Loop module.

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#45]
Currently, these might be undetected, but they are a form of loops.

**Comment by msimmon6** [comment]
Looking more into it, I think labels are required to be in front of other loops - so its looping structure is still caught. I no longer think this is necessary.

**Comment by Algomorph** [comment]
That's true, there is no "goto". I think then this can be closed. I'll see about handling labels in the parser separately.
