### ISSUE TITLE
Test Module: tests without @Test annotation aren't picked up

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#48]
The test module completely ignores test methods without the @test annotation. For better detection, it should find classes that extend "TestCase" and the methods within them that start with "test".

**Comment by Algomorph** [comment]
Actually, I'm not sure that this bug is valid. I recall recently trying to make a JUnit 4 test w/o an @Test annotation. However, this might be a valid feature. E.g. if the student writes the tests properly, but forgets about the annotations, this doesn't mean he should get all points off for the tests... The criterion for this would be that the class extents TestCase, not necessarily that test starts with "test".

Action items:

- Confirm that test methods whose names start with "test" but that don't have the @Test annotation (within the JUnit TestCase) don't work / aren't picked up by eclipse.
- If these truly don't work, change this issue from "bug" to "feature" and implement the scenario described above, to mark the methods with "missing-test-annotation" error in the code panel + tag in the code at the method signature.

**Comment by Algomorph** [comment]
I'm going to put the foot down here and redefine this as a feature request, i.e. ability to pick up on students writing tests but forgetting the @Test annotations. This is also going to moved to the board for the next release.

**Comment by danzou56** [comment]
I'm wondering, what about if `method1` was trying to be detected in the following situation:

```java
@Test
public void testMethod() {
    helper();
}

private void unnecessaryHelper() {
    method1();
}
```

Here, @Test hasn't been forgotten, but `method1` isn't in a method marked by @Test, but it's certainly tested.

**Comment by msimmon6** [comment]
This is #50 which I implemented two days ago :)

**Comment by danzou56** [comment]
Perhaps I should be more diligent with searching through PRs/issues :)

**Comment by msimmon6** [comment]
I was bored of node stuff and decided to tackle this in my most recent commit (629005a7ef2d1b2facde18fbd889c8d3a7d07843). I decided to interpret "test without `@Test` annotation" as anything in the testing file that does not have `@Test` and is not a helper method to a `@Test` method, or basically anything "unused" in a test file. Right now it is basically a chunk of copy-pasted code from checking the regular tested code and has some redundancies, but I'm not too worried about how it looks since we will be changing the structure later for code entities. Lmk what you think of my definition.

**Comment by Algomorph** [comment]
I think this makes sense, but perhaps we ought to make a `CodeEntity` later that would let the grader know that the student didn't use the `@Test` annotation, so the student might, say, lose a point if they don't use the `@Test` anywhere at all.

**Comment by msimmon6** [comment]
I think you already implemented this in the overhaul @Algomorph - shouldn't this be closed?
