### ISSUE TITLE
Test Module FP on ealoba, Proj 6, Fall 2020

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#51]
keySet is being tested on line 113 of StuentTests.java, but isn't getting registered by the Test Module (may be, something to do with the cast that's preceding the call).

**Comment by msimmon6** [comment]
I have fixed this issue, but an issue in the same file occurs where it's not picking up the rightRootLeftTraversal test - I think it has something to do with an ExpressionStatement.

**Comment by msimmon6** [comment]
It took a month, but I've realized that it's actually because there's no Test annotation. All good here!
