### ISSUE TITLE
Performance issue / Infinite loop?

### ISSUE THREAD

**Issue by Algomorph** [Algomorph/CodeGrader#57]
nfox submission of Final Exam for CMSC132 Fall2020

**Comment by msimmon6** [comment]
I am getting a similar issue on tadetunj's P1, so this is probably a newer issue (it totally worked before)

**Comment by msimmon6** [comment]
Also jbaile11's Final Exam

**Comment by msimmon6** [comment]
After examining stuff, it seems the line in the code that stalls everything is 110 of utilities.java:
const codeText = $($(trCodeLine).find("div.gwt-Label")[0]).text();

It also seems to halt almost entirely due to MapOfCodes.java for nfox, and both MapOfCodes and CMSC132Sorter for jbaile11. Not sure what's special about these, but it's not an infinite loop, at least!

**Comment by Algomorph** [comment]
@msimmon6 , thanks, I'll check what's happening here.
https://github.com/Algomorph/CodeGrader/blob/163d80289a0f15b11e100de2a36c33b632f729ac/utilities.js#L108

**Comment by Algomorph** [comment]
Might also be true for 

asunda
Pedram's CMSC131 P3

**Comment by msimmon6** [comment]
asunda was a separate issue, since fixed

**Comment by Algomorph** [comment]
This is actually an issue with the parser (at least for nfox in OP). CMSC131 / 2021 P4 aboud seems to be suffering from the same issue.

The loop seems to be on https://github.com/Algomorph/CodeGrader/blob/ecd07085a86e8c4df09e2b90cfce3e8fe36bc907/utilities.js#L60

I'm looking into that RN.

**Comment by Algomorph** [comment]
nfox bug fixed (it wasn't easy!) in javaparser and the lambdaSupport#55 branch here. jbaile11 is a separate bug, but should be easier to fix now that I built up the infrastruture for that.

**Comment by Algomorph** [comment]
Just fixed for jbaile11 as well. Unfortunately, processing is still horrendously slow on lines such as:
```Java
        int z = ((((x + ((x + 1) + 1))) + 1));
```
This is due to the nature of the parser. I'm not sure how to resolve this right now, but I'll open a separate performance issue for this.
