### ISSUE TITLE
Review not responding when including certain files

### ISSUE THREAD

**Issue by afloresv** [Algomorph/CodeGrader#75]
**Describe the bug**
When opening the REVIEW link, the tab becomes unresponsive. The issue comes from including certain files in the "filesToCheck". Some of the conflicting files are included in the following zip file: [Archive.zip](https://github.com/Algomorph/CodeGrader/files/5952775/Archive.zip)

**Where did the bug occur**
Instructor & Course: Nelson's CMSC132
Project name on Submit Server: Project # 1
Student directory id: all

**Desktop (please complete the following information):**
 - OS: Mac OS

**Comment by Algomorph** [comment]
@afloresv , I think we merged in a few fixes that probably took care of the issues in these files. Could you re-test the above with the developer version from the master branch of the repository?

**Comment by Algomorph** [comment]
Was fixed with either #57 and/or some updates to the indentation module.
