### ISSUE TITLE
Not identifying method calls correctly (student tests)

### ISSUE THREAD

**Issue by afloresv** [Algomorph/CodeGrader#78]
**Describe the bug**
Some of the listed method calls are not being correctly identified, leading to false negative results when checking for student test calls. See the following example, where the method **getPlaylistsNames** from the **TubeVideosManager** class is marked as not called in the student tests, but you can see there are several calls in the tests.
<img width="1512" alt="Example" src="https://user-images.githubusercontent.com/2859447/108236274-b717b180-7114-11eb-99e0-80c6ca513cb4.png">

**Where did the bug occur**
Instructor & Course: Nelson's CMSC132
Project name on Submit Server: Proj 1

**Desktop (please complete the following information):**
 - OS: Mac OS / Windows

**Comment by msimmon6** [comment]
#85 should take care of this
