### ISSUE TITLE
More than one student found when no such student exists on grade server

### ISSUE THREAD

**Issue by danzou56** [Algomorph/CodeGrader#79]
**Describe the bug**
Alert on grade server reports "More than one student with that directory ID found" when, in fact, no such student exists.

I would guess this occurs when a student has made a submission, but dropped the course. 

**Where did the bug occur**
Instructor & Course: Pedram's CMSC131 Sp2021
Project name on Submit Server: Proj 2
Student directory id: rshort

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional info**
![image](https://user-images.githubusercontent.com/11336005/109449133-acfb8a00-7a15-11eb-8770-f550cde458f6.png)

**Comment by Algomorph** [comment]
Yes, I remember this happening to me too. Thank you for filing the report!
