### ISSUE TITLE
Code hang for P2 samohmar

### ISSUE THREAD

**Issue by danzou56** [Algomorph/CodeGrader#80]
**Describe the bug**
Code hang (Aw snap! RESULT_CODE_HUNG) on Proj 2 samohmar

**Where did the bug occur**
Instructor & Course: Pedram's CMSC131
Project name on Submit Server: Proj 2
Student directory id: samohmar

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Algomorph** [comment]
Thanks for reporting, we'll investigate!

**Comment by Algomorph** [comment]
Ditto for `ssharm11` and `tbarry85`, again on Proj 2 (JavaLoops) in Pedram's CMSC131

**Comment by msimmon6** [comment]
Fixed on the most recent commit

**Comment by danzou56** [comment]
#84
