### ISSUE TITLE
"enhanced for loop body" isn't an enhanced for loop

### ISSUE THREAD

**Issue by danzou56** [Algomorph/CodeGrader#81]
**Describe the bug**
Code grader reports bad indentation on close brace of "enhanced for loop body" when loop isn't an enhanced for loop. 

**Where did the bug occur**
Instructor & Course: Pedram's CMSC131
Project name on Submit Server: Proj 2
Student directory id: e.g. rshort, shopkin3 (Convert.java:35-39)
**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional info**
Certainly possible that I'm misunderstanding this and I should be interpreting this as bad indentation on close brace of general loop, in which case I would suggest a different wording for the error message.

**Comment by Algomorph** [comment]
I confirm this, it must be a minor bug in the brace set classification system within the brace style module. Thanks, Dan!
